config/routes.rb
Rails.application.routes.draw do
  resources :milestones

  resources :sprojects

  get 'sessions/new'

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"

   get "log_in" => "sessions#new", :as => "log_in"
   get "log_out" => "sessions#destroy", :as => "log_out"
   get "grade_quiz" => "quizzes#grade", :as => "grade_quiz"
   get "add_subject" => "subjects#add", :as => "add_subject"

  resources :sessions

  resources :users

  resources :students

  resources :topics

  resources :subjects

  resources :quizzes

  resources :questions

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :milestone

	validates :name, presence: true
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :sproject
	has_many :goals

	validates :name, presence: true;
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/projects_subject.rb
class ProjectsSubject < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base

	has_many :topics, through: :topics_questions
	has_many :topics_questions
	has_many :options

	has_attached_file :image,:url => "/images/questions/:id/image.:extension", :path => ":rails_root/public/images/questions/:id/image.:extension", :default_url => '/images/missing_:style.png'
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :content, presence: true

	def correct_option
		self.options.where(correct: true).first
	end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	belongs_to :student
	has_many :questions, through: :quizzes_questions
	has_many :quizzes_questions

	#choose questions from specified topic, add questions to quiz
	def generate(topics )
		topics = [] if topics.nil?
		unless self.no_of_questions
			self.no_of_questions = 10
		end
		unless topics.empty?
			ids = TopicsQuestion.where({topic_id: topics.sample.id, weight: (self.student.level - 1..self.student.level + 1)}).pluck(:question_id).shuffle[0..9]
		else
			ids = TopicsQuestion.where(weight: (self.student.level - 1..self.student.level + 1)).pluck(:question_id).shuffle[0..9]
		end
		if ids.length < no_of_questions
			unless topics.empty?
				ids = ids +  TopicsQuestion.where({topic_id: topics.sample.id, weight: (self.student.level - 1..self.student.level + 1)}).pluck(:question_id).shuffle[0..no_of_questions - ids.length]
			else
				ids = ids + TopicsQuestion.pluck(:question_id).shuffle[0..no_of_questions - ids.length]
			end
		end
		questions = Question.where(id: ids)
		self.questions = questions
		questions.each {|question| question.used = question.used + 1
			question.save
		}
	end

	def grade (answers)
		grade = 0
		self.questions.each do |question|
			if answers["#{question.id}"].to_i == question.correct_option.id
				puts "correct"
				grade = grade + 1
				if question.answered.nil? 
						question.answered = 1
					else
						question.answered = question.answered+ 1
					end
				topics = question.topics
				topics.each do |topic|
					student_topic = StudentsTopic.find_or_create_by(student_id: self.student_id, topic_id: topic.id)
					if student_topic.score.nil? 
						student_topic.score = 1
					else
						student_topic.score = student_topic.score + 1
					end
					student_topic.save
				end
			end
		end		
		self.result = grade
	end
end

app/models/sproject.rb
class Sproject < ActiveRecord::Base
	has_many :students, through: :students_sprojects
	has_many :students_sprojects
	has_many :subjects, through: :subjects_sprojects
	has_many :subjects_sprojects
	has_many :milestones

	validates :name, presence: true;
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user

	has_many :subjects, through: :students_subjects
	has_many :students_subjects
	has_many :topics, through: :students_topics
	has_many :students_topics
	has_many :sprojects, through: :students_sprojects
	has_many :students_sprojects

	def get_subject_level (subject_id)
		sum = 0;
		count = 0;
		Subject.find(subject_id).topics.each do |topic| 
			if self.topics.exists?(topic.id) 
				sum = sum + (StudentsTopic.where(topic_id: topic.id, student_id: self.id).first.score).to_i
				count = count + 1
			end
		end
		if count > 0
			sum/count
		else
			0
		end
	end

	def get_all_subjects
		result = []
		self.subjects.each  do |subject|
			result.push( {"name" => subject.name,"level" => self.get_subject_level(subject.id)})
		end
		result
	end
end

app/models/students_topic.rb
class StudentsTopic < ActiveRecord::Base
	belongs_to :student 
	belongs_to :topic 
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	
	has_many :children, class_name: "Subject", foreign_key: "subject_id"
	has_many :students, through: :students_subjects
	has_many :students_subjects
	has_many :topics, through: :subjects_topics
	has_many :subjects_topics

	belongs_to :parent, class_name: "Subject", foreign_key: "subject_id"

	validates :name, presence: true

	def is_basic?
		self.parent.nil?
	end

	def is_barren?
		self.children.empty?
	end

	def to_node
		result = {}
		keys = self.attributes.keys
		keys.each{|key| result[key] = attributes[key]}
		result["children"] = self.children.map {|c| c.to_node}
	    result
  	end
end

app/models/subjects_topic.rb
class SubjectsTopic < ActiveRecord::Base
	belongs_to :subject 
	belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :subjects, through: :subjects_topics
	has_many :subjects_topics

	has_many :questions, through: :topics_questions
	has_many :topics_questions

	validates :name, presence: true
end

app/models/topics_question.rb
class TopicsQuestion < ActiveRecord::Base
	belongs_to :topic 
	belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base

	has_one :student

	 before_save :encrypt_password
	  attr_accessor :password
	  attr_accessor :password_confirmation

	def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end

	def self.authenticate(name, password)
  	  user = find_by_name(name)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
   end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :grade]
  before_action :require_authorization
  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  def grade
    @quiz.grade(params[:answers])
    @answers = params[:answers]

  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.student_id = current_user.student.id
    @quiz.generate (quiz_params[:topics])
    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: '' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:result, :no_of_questions, :topics)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :no_of_questions %><br>
    <%= f.number_field :no_of_questions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/grade.html.erb
<div class="col-xs-12">
<p id="notice"><%= notice %></p>

<% @quiz.questions.each do |question| %>
	<div class="question panel panel-default">
		<div class ="panel-heading">
		<%= image_tag question.image.url %>
		<p>Q: <%= question.content %><p>
		</div>
		<div class="options row panel-body">
			<p> Your answer was: <%= question.options.find(@answers["#{question.id}"]).content%></p>
			<p> The correct answer is: <%= question.correct_option.content%></p>
			<% if question.correct_option.description %>
				<p> Explanation: <%= question.correct_option.description %></p>
			<% end %>
		</div>
	</div>
<% end %>

<%= link_to "Back to Profile", student_path(current_user.student), class: "btn btn-lg btn-default" %>

</div>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Result</th>
      <th>No of questions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.result %></td>
        <td><%= quiz.no_of_questions %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<div class="col-xs-12">
<p id="notice"><%= notice %></p>


<%= form_tag grade_quiz_path, :role => "form", :method => "get" do %>
<%= hidden_field_tag 'id', @quiz.id%>
<% @quiz.questions.each do |question| %>
	<div class="question panel panel-default">
		<div class ="panel-heading">
		<%= image_tag question.image.url %>
		<p>Q: <%= question.content %><p>
		</div>
		<div class="options row panel-body">
			<% question.options.each do |option| %>
				<div class="col-xs-6">
					<%= option.content %>
					<%= radio_button_tag "answers[#{question.id}]", option.id%>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

<div class="controls">
<button type="submit" class ="btn btn-success" >Submit</button> 
</div>
<% end %>
</div>