config/routes.rb
Rails.application.routes.draw do
  resources :milestones

  resources :sprojects

  get 'sessions/new'

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"

   get "log_in" => "sessions#new", :as => "log_in"
   get "log_out" => "sessions#destroy", :as => "log_out"
   get "grade_quiz" => "quizzes#grade", :as => "grade_quiz"
   get "add_subject" => "subjects#add", :as => "add_subject"

  resources :sessions

  resources :users

  resources :students

  resources :topics

  resources :subjects

  resources :quizzes

  resources :questions

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :milestone

	validates :name, presence: true
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :sproject
	has_many :goals

	validates :name, presence: true;
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base

	has_many :topics, through: :topics_questions
	has_many :topics_questions
	has_many :options

	has_attached_file :image,:url => "/images/questions/:id/image.:extension", :path => ":rails_root/public/images/questions/:id/image.:extension", :default_url => '/images/missing_:style.png'
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :content, presence: true

	def correct_option
		self.options.where(correct: true).first
	end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	belongs_to :student
	has_many :questions, through: :quizzes_questions
	has_many :quizzes_questions

	#choose questions from specified topic, add questions to quiz
	def generate(topics )
		topics = [] if topics.nil?
		unless self.no_of_questions
			self.no_of_questions = 10
		end
		unless topics.empty?
			ids = TopicsQuestion.where({topic_id: topics.sample.id, weight: (self.student.level - 1..self.student.level + 1)}).pluck(:question_id).shuffle[0..9]
		else
			ids = TopicsQuestion.where(weight: (self.student.level - 1..self.student.level + 1)).pluck(:question_id).shuffle[0..9]
		end
		if ids.length < no_of_questions
			unless topics.empty?
				ids = ids +  TopicsQuestion.where({topic_id: topics.sample.id, weight: (self.student.level - 1..self.student.level + 1)}).pluck(:question_id).shuffle[0..no_of_questions - ids.length]
			else
				ids = ids + TopicsQuestion.pluck(:question_id).shuffle[0..no_of_questions - ids.length]
			end
		end
		questions = Question.where(id: ids)
		self.questions = questions
		questions.each {|question| question.used = question.used + 1
			question.save
		}
	end

	def grade (answers)
		grade = 0
		self.questions.each do |question|
			if answers["#{question.id}"].to_i == question.correct_option.id
				puts "correct"
				grade = grade + 1
				if question.answered.nil? 
						question.answered = 1
					else
						question.answered = question.answered+ 1
					end
				topics = question.topics
				topics.each do |topic|
					student_topic = StudentsTopic.find_or_create_by(student_id: self.student_id, topic_id: topic.id)
					if student_topic.score.nil? 
						student_topic.score = 1
					else
						student_topic.score = student_topic.score + 1
					end
					student_topic.save
				end
			end
		end		
		self.result = grade
	end
end

app/models/sproject.rb
class Sproject < ActiveRecord::Base
	has_many :students, through: :students_sprojects
	has_many :students_sprojects
	has_many :subjects, through: :subjects_sprojects
	has_many :subjects_sprojects
	has_many :milestones

	validates :name, presence: true;
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user

	has_many :subjects, through: :students_subjects
	has_many :students_subjects
	has_many :topics, through: :students_topics
	has_many :students_topics
	has_many :sprojects, through: :students_sprojects
	has_many :students_sprojects

	def get_subject_level (subject_id)
		sum = 0;
		count = 0;
		Subject.find(subject_id).topics.each do |topic| 
			if self.topics.exists?(topic.id) 
				sum = sum + (StudentsTopic.where(topic_id: topic.id, student_id: self.id).first.score).to_i
				count = count + 1
			end
		end
		if count > 0
			sum/count
		else
			0
		end
	end

	def get_all_subjects
		result = []
		self.subjects.each  do |subject|
			result.push( {"name" => subject.name,"level" => self.get_subject_level(subject.id)})
		end
		result
	end
end

app/models/students_topic.rb
class StudentsTopic < ActiveRecord::Base
	belongs_to :student 
	belongs_to :topic 
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	
	has_many :children, class_name: "Subject", foreign_key: "subject_id"
	has_many :students, through: :students_subjects
	has_many :students_subjects
	has_many :topics, through: :subjects_topics
	has_many :subjects_topics

	belongs_to :parent, class_name: "Subject", foreign_key: "subject_id"

	validates :name, presence: true

	def is_basic?
		self.parent.nil?
	end

	def is_barren?
		self.children.empty?
	end

	def to_node
		result = {}
		keys = self.attributes.keys
		keys.each{|key| result[key] = attributes[key]}
		result["children"] = self.children.map {|c| c.to_node}
	    result
  	end
end

app/models/subjects_topic.rb
class SubjectsTopic < ActiveRecord::Base
	belongs_to :subject 
	belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :subjects, through: :subjects_topics
	has_many :subjects_topics

	has_many :questions, through: :topics_questions
	has_many :topics_questions

	validates :name, presence: true
end

app/models/topics_question.rb
class TopicsQuestion < ActiveRecord::Base
	belongs_to :topic 
	belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base

	has_one :student

	 before_save :encrypt_password
	  attr_accessor :password
	  attr_accessor :password_confirmation

	def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end

	def self.authenticate(name, password)
  	  user = find_by_name(name)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
   end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav">
      <li><%= link_to "Home", student_path(current_user.student.id) %></li>
      <li><%= link_to "Subjects",subjects_path %></li>
      <li><%= link_to "Projects",sprojects_path %></li>
      <li><%= link_to "Topics",topics_path %></li>
      </ul>
      <!-- <ul class="nav navbar-nav">
      <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">Link</b></a></li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sub Menu <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/accounts">Sub Menu Link</a></li>
        </ul>
      </li>

    </ul> -->

    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Me</p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= session[:name] %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
         
          <li class="divider"></li>
          <li><%= link_to 'Logout', log_out_path %></li>
        </ul>
      </li>
    </ul>

  </div>
</nav>


<div class="row">
	<%= yield %>
</div>
</div>

</body>
</html>